[package]
name = "pac-git"
version = "0.1.0"
authors = ["bimorphism <dhillonwilk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
getopts = "0.2"
expanduser = "1.2.2"